version: "3"
services:
  dbpostgres:
    ports:
      - "5432:5432"
    container_name: auth_db
    image: "postgres:12.5"
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "itsallgood"
      POSTGRES_DB: "travel"
